### ISSUE TITLE
Failed to built under fedora 25

### ISSUE THREAD

**Issue by biaji** [OpenPathView/raw2dng#1]
Got errors while build, I believe it just a build config problem. but as i'm newbee to c.  So....

make[1]: Entering directory '/home/biaji/SOURCE/raw2dng/common'
g++ -c -pipe -O2 -fPIC  -I/usr/lib64/qt4/mkspecs/linux-g++ -I. -o write_dng.o write_dng.cpp
write_dng.cpp: In member function 'bool TIFF_Content::write_dng(FILE*, bool, bool, bool)':
write_dng.cpp:509:55: error: narrowing conversion of '-3814' from 'int' to 'dword {aka long unsigned int}' inside { } [-Wnarrowing]
          { -627,10000}, {  796,10000}, { 7550,10000}, };
                                                       ^
write_dng.cpp:509:55: error: narrowing conversion of '-225' from 'int' to 'dword {aka long unsigned int}' inside { } [-Wnarrowing]
write_dng.cpp:509:55: error: narrowing conversion of '-6649' from 'int' to 'dword {aka long unsigned int}' inside { } [-Wnarrowing]
write_dng.cpp:509:55: error: narrowing conversion of '-627' from 'int' to 'dword {aka long unsigned int}' inside { } [-Wnarrowing]
write_dng.cpp:515:54: error: narrowing conversion of '-2583' from 'int' to 'dword {aka long unsigned int}' inside { } [-Wnarrowing]
          {-1307,10000}, { 1407,10000}, { 7354,10000} };
                                                      ^
write_dng.cpp:515:54: error: narrowing conversion of '-1036' from 'int' to 'dword {aka long unsigned int}' inside { } [-Wnarrowing]
write_dng.cpp:515:54: error: narrowing conversion of '-8051' from 'int' to 'dword {aka long unsigned int}' inside { } [-Wnarrowing]
write_dng.cpp:515:54: error: narrowing conversion of '-1307' from 'int' to 'dword {aka long unsigned int}' inside { } [-Wnarrowing]
write_dng.cpp:530:55: error: narrowing conversion of '-3749' from 'int' to 'dword {aka long unsigned int}' inside { } [-Wnarrowing]
          { 2313,10000}, { 6603,10000}, { 1061,10000}, };
                                                       ^
write_dng.cpp:530:55: error: narrowing conversion of '-1607' from 'int' to 'dword {aka long unsigned int}' inside { } [-Wnarrowing]
write_dng.cpp:530:55: error: narrowing conversion of '-3375' from 'int' to 'dword {aka long unsigned int}' inside { } [-Wnarrowing]
write_dng.cpp:537:54: error: narrowing conversion of '-5368' from 'int' to 'dword {aka long unsigned int}' inside { } [-Wnarrowing]
          {  778,10000}, { 9028,10000}, {  211,10000} };
                                                      ^
write_dng.cpp:537:54: error: narrowing conversion of '-113' from 'int' to 'dword {aka long unsigned int}' inside { } [-Wnarrowing]
write_dng.cpp:537:54: error: narrowing conversion of '-4969' from 'int' to 'dword {aka long unsigned int}' inside { } [-Wnarrowing]
write_dng.cpp:734:43: warning: narrowing conversion of '(image_W - 16)' from 'int' to 'dword {aka long unsigned int}' inside { } [-Wnarrowing]
    rational DefaultCropSize[2] = {{image_W-16,1},{image_H-4,1}};
                                    ~~~~~~~^~~
write_dng.cpp:734:58: warning: narrowing conversion of '(image_H - 4)' from 'int' to 'dword {aka long unsigned int}' inside { } [-Wnarrowing]
    rational DefaultCropSize[2] = {{image_W-16,1},{image_H-4,1}};
                                                   ~~~~~~~^~
Makefile:280: recipe for target 'write_dng.o' failed
make[1]: *** [write_dng.o] Error 1

**Comment by Valdimus** [comment]
Hello, as far as I remember, raw2dng not working very well on Linux, but raw2nef work like a charm. 

On my platform (Ubuntu 16.04) these messages are warnings, not errors. You can disable it with the flag -Wno-narrowing found in https://gcc.gnu.org/onlinedocs/gcc/C_002b_002b-Dialect-Options.html.

Add this to the file raw2dng.pro:
QMAKE_CXXFLAGS += -Wno-narrowing 

It should work.

**Comment by biaji** [comment]
Yes, it's worked. Thank you!

**Comment by biaji** [comment]
And you are right that raw2dng not working.  Exif info all massed. I'm trying to figure it out. 

Thanks again!

**Comment by Valdimus** [comment]
You are Welcome, and thanks for testing on Fedora. If you figure it out, it would be great!

**Comment by chrylis** [comment]
I'm experiencing the same problem on Gentoo with gcc 6.4.0. It seems it would be better to fix the implicit narrowing, which is likely to be causing the EXIF problems.
